name: LoginLogs
version: 1.3.2
description: Records player logins and logouts
author: acomputerdog
main: net.acomputerdog.loginlogs.PluginLoginLogs

commands:
  lastlog:
    description: Look up log info for a player
    permission: loginlogs.command.lastlog
    usage: Incorrect usage!  Use /lastlog <name | uuid>
    aliases: ll
  lastlogin:
    description: Look up login info for a player
    permission: loginlogs.command.lastlogin
    usage: Incorrect usage!  Use /lastlogin <name | uuid>
    aliases: lli
  lastlogout:
    description: Look up logout info for a player
    permission: loginlogs.command.lastlogout
    usage: Incorrect usage!  Use /lastlogout <name | uuid>
    aliases: llo
  lastlogins:
    description: Look up recent player logins
    permission: loginlogs.command.lastlogins
    usage: Incorrect usage!  Use /lastlogins
    aliases: [lls, lastlogs]

permissions:
  loginlogs.command.*:
    description: Use all loginlogs permissions
    default: op
    children:
      lastlog.command.lastlog: true
      lastlog.command.lastlogin: true
      lastlog.command.lastlogout: true
      lastlog.command.lastlogins: true
  loginlogs.command.lastlog:
    description: Use /lastlog
    default: op
  loginlogs.command.lastlogin:
    description: Use /lastlogin
    default: op
  loginlogs.command.lastlogout:
    description: Use /lastlogout
    default: op
  loginlogs.command.lastlogins:
    description: Use /lastlogins
    default: op
