name: LoginLogs
version: 1.4.0
description: Records player logins and logouts
author: acomputerdog
main: net.acomputerdog.loginlogs.PluginLoginLogs

commands:
  lastlog:
    description: Look up log info for a player
    permission: loginlogs.command.lastlog
    usage: Use /lastlog <name | uuid>
    aliases: ll
  lastlogin:
    description: Look up player's last login
    permission: loginlogs.command.lastlogin
    usage: Use /lastlogin <name | uuid>
    aliases: lli
  lastlogout:
    description: Look up player's last logout
    permission: loginlogs.command.lastlogout
    usage: Use /lastlogout <name | uuid>
    aliases: llo
  lastlogins:
    description: Look up recent player logins
    permission: loginlogs.command.lastlogins
    usage: Use /lastlogins
    aliases: [lls, lastlogs]
  firstlogin:
    description: Look up player's first login
    permission: loginlogs.command.firstlogin
    usage: /firstlogin <name | uuid>
    aliases: fli

permissions:
  loginlogs.command.*:
    description: Use all loginlogs commands
    default: op
    children:
      lastlog.command.lastlog: true
      lastlog.command.lastlogin: true
      lastlog.command.lastlogout: true
      lastlog.command.lastlogins: true
      lastlog.command.firstlogin: true
  loginlogs.command.lastlog:
    description: Use /lastlog
    default: op
  loginlogs.command.lastlogin:
    description: Use /lastlogin
    default: op
  loginlogs.command.lastlogout:
    description: Use /lastlogout
    default: op
  loginlogs.command.lastlogins:
    description: Use /lastlogins
    default: true
  loginlogs.command.firstlogin:
    description: Use /firstlogin
    default: op
