name: ${name}
version: ${version}
description: Records player logins and logouts
author: acomputerdog
main: net.acomputerdog.loginlogs.PluginLoginLogs
api-version: 1.13

commands:
  lastlog:
    description: Look up log info for a player
    permission: loginlogs.command.lastlog
    usage: /lastlog <name | uuid>
    aliases: llp
    min-args: 1
    max-args: 1
  lastlogins:
    description: Look up recent player logins
    permission: loginlogs.command.lastlogins
    usage: /lastlogins
    aliases: [ll, lli, llis, lastlogs]
  lastlogouts:
    description: Look up recent player logouts
    permission: loginlogs.command.lastlogouts
    usage: /lastlogouts
    aliases: [llo, llos]

permissions:
  loginlogs.command.*:
    description: Use all loginlogs commands
    default: op
    children:
      lastlog.command.lastlog: true
      lastlog.command.lastlogins: true
  loginlogs.command.lastlog:
    description: Use /lastlog
    default: op
  loginlogs.command.lastlogins:
    description: Use /lastlogins
    default: true
  loginlogs.command.lastlogouts:
    description: Use /lastlogouts
    default: true
